version: "3.3"

services:

  ########################### base images: ###########################



  base:
    build: base
    image: base
  basepythonnodejs:
    build: basepythonnodejs
  basescala:
    build: basescala
    image: basescala



  ########################### databases: ###########################



  couchlocal:
    image: klaemo/couchdb:1.6.1
    ports:
      - "5984:5984"
    expose:
      - "5984"
    volumes:
      - $II_CLONE_PATH/dockerdata/couchdb:/usr/local/var/lib/couchdb
  couchproxy:
    build: couchproxy
    image: couchproxy
    environment:
      CLOUDANT_USERNAME:
      CLOUDANT_AUTHORIZATION_HEADER:
  postgres:
    image: "postgres:9.5"
    environment:
      POSTGRES_PASSWORD: asdf



  ########################### services: ###########################

  scheduler:
    build:
      context: scheduler
      args:
        github_username: "${GITHUB_USERNAME}"
        github_access_token: "${GITHUB_ACCESS_TOKEN}"
    links:
      - couchlocal:couch
    ports:
      - "9600:8000"
    environment:
      II_SCHEDULER_HOST: 0.0.0.0
      II_SCHEDULER_PORT: 8000
      II_COUCH_HOST: couch
      II_COUCH_PORT: 5984
      II_COUCH_NAME: scheduler
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - ${II_CLONE_PATH}/scheduler:/app/scheduler

  schedulergrunt:
    build:
      context: scheduler_grunt
      args:
        github_username: "${GITHUB_USERNAME}"
        github_access_token: "${GITHUB_ACCESS_TOKEN}"
    ports:
      - "9601:9601"
      - "35729:35729"
    volumes:
      - ${II_CLONE_PATH}/django_scheduler:/app/django_scheduler

  schedulerfrontend:
    build:
      context: scheduler_frontend
      args:
        github_username: "${GITHUB_USERNAME}"
        github_access_token: "${GITHUB_ACCESS_TOKEN}"
    ports:
      - "9602:8000"
    links:
      - scheduler:scheduler
      - postgres:postgres
    volumes:
      - ${II_CLONE_PATH}/django_scheduler:/app/django_scheduler
      - ${II_CLONE_PATH}/scheduler_frontend:/app/scheduler_frontend
      - ${II_CLONE_PATH}/runner/ii/scheduler_frontend/settings.py:/app/settings_docker.py

  schedulerscripts:
    build:
      context: scheduler_scripts
      args:
        github_username: "${GITHUB_USERNAME}"
        github_access_token: "${GITHUB_ACCESS_TOKEN}"
    links:
      - scheduler:scheduler
      - postgres:postgres
      - couchlocal:couch
    volumes:
      - ${II_CLONE_PATH}/scheduler_scripts:/app/scheduler_scripts
