version: "3.7"

services:



  ########################### databases: ###########################



  couch:
    image: couchdb:2.3
    ports:
      - "5984:5984"
    expose:
      - "5984"
    volumes:
      - $II_CLONE_PATH/dockerdata/couchdb:/usr/local/var/lib/couchdb
  postgres:
    image: "postgres:9.5"
    environment:
      POSTGRES_PASSWORD: asdf
    ports:
      - "5432:5432"
    expose:
      - "5432"



  ########################### services: ###########################

  scheduler_backend:
    build:
      context: ${II_CLONE_PATH}/scheduler
    links:
      - couch:couch
    ports:
      - "9600:8000"
    environment:
      II_SCHEDULER_HOST: 0.0.0.0
      II_SCHEDULER_PORT: 8000
      II_COUCH_HOST: couch
      II_COUCH_PORT: 5984
      II_COUCH_NAME: scheduler
      II_CLONE_PATH: /app
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - ${II_CLONE_PATH}/scheduler:/app/scheduler

  scheduler_frontend:
    build:
      context: ${II_CLONE_PATH}/django_scheduler
    ports:
      - "9601:9601"
      - "35729:35729"
      - "8000:8000"
    environment:
      II_CLONE_PATH: /app
      II_POSTGRES_HOST: postgres
      II_POSTGRES_USER: postgres
      II_POSTGRES_PASSWORD: asdf
      II_SCHEDULER_HOST: scheduler
      II_SCHEDULER_PORT: 8000
    links:
      - scheduler_backend:scheduler
      - postgres:postgres
    volumes:
      - ${II_CLONE_PATH}/django_scheduler:/app/django_scheduler

  scheduler_scripts:
    build:
      context: ${II_CLONE_PATH}/scheduler_scripts
    links:
      - scheduler_backend:scheduler
      - postgres:postgres
      - couch:couch
    volumes:
      - ${II_CLONE_PATH}/scheduler_scripts:/app/scheduler_scripts
